[package]
name = "poprako-service"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bcrypt.workspace = true
chrono.workspace = true
dashmap.workspace = true
redis.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
poprako-core = { path = "../poprako-core" }
poprako-dto = { path = "../poprako-dto" }
poprako-entity = { path = "../poprako-entity" }
poprako-repository = { path = "../poprako-repository" }
