/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedShellRouteRouteImport } from './routes/_authenticated/_shell/route'
import { Route as AuthenticatedTranslatorRouteRouteImport } from './routes/_authenticated/translator/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedShellIndexRouteImport } from './routes/_authenticated/_shell/index'
import { Route as AuthenticatedShellComicPlaygroundIndexRouteImport } from './routes/_authenticated/_shell/comic-playground/index'
import { Route as AuthenticatedShellMemberListIndexRouteImport } from './routes/_authenticated/_shell/member-list/index'
import { Route as AuthenticatedShellSettingsIndexRouteImport } from './routes/_authenticated/_shell/settings/index'
import { Route as AuthenticatedShellSystemMailIndexRouteImport } from './routes/_authenticated/_shell/system-mail/index'
import { Route as AuthenticatedShellUtilitiesIndexRouteImport } from './routes/_authenticated/_shell/utilities/index'
import { Route as AuthenticatedShellWorkspaceIndexRouteImport } from './routes/_authenticated/_shell/workspace/index'
import { Route as AuthenticatedTranslatorChapterIdPageIdIndexRouteImport } from './routes/_authenticated/translator/$chapterId/$pageId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRouteRoute = AuthenticatedShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTranslatorRouteRoute =
  AuthenticatedTranslatorRouteRouteImport.update({
    id: '/translator',
    path: '/translator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellIndexRoute = AuthenticatedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedShellRouteRoute,
} as any)
const AuthenticatedShellComicPlaygroundIndexRoute =
  AuthenticatedShellComicPlaygroundIndexRouteImport.update({
    id: '/comic-playground/',
    path: '/comic-playground/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellMemberListIndexRoute =
  AuthenticatedShellMemberListIndexRouteImport.update({
    id: '/member-list/',
    path: '/member-list/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellSettingsIndexRoute =
  AuthenticatedShellSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellSystemMailIndexRoute =
  AuthenticatedShellSystemMailIndexRouteImport.update({
    id: '/system-mail/',
    path: '/system-mail/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellUtilitiesIndexRoute =
  AuthenticatedShellUtilitiesIndexRouteImport.update({
    id: '/utilities/',
    path: '/utilities/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellWorkspaceIndexRoute =
  AuthenticatedShellWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedTranslatorChapterIdPageIdIndexRoute =
  AuthenticatedTranslatorChapterIdPageIdIndexRouteImport.update({
    id: '/$chapterId/$pageId/',
    path: '/$chapterId/$pageId/',
    getParentRoute: () => AuthenticatedTranslatorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedShellIndexRoute
  '/translator': typeof AuthenticatedTranslatorRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/comic-playground/': typeof AuthenticatedShellComicPlaygroundIndexRoute
  '/member-list/': typeof AuthenticatedShellMemberListIndexRoute
  '/settings/': typeof AuthenticatedShellSettingsIndexRoute
  '/system-mail/': typeof AuthenticatedShellSystemMailIndexRoute
  '/utilities/': typeof AuthenticatedShellUtilitiesIndexRoute
  '/workspace/': typeof AuthenticatedShellWorkspaceIndexRoute
  '/translator/$chapterId/$pageId/': typeof AuthenticatedTranslatorChapterIdPageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedShellIndexRoute
  '/translator': typeof AuthenticatedTranslatorRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/comic-playground': typeof AuthenticatedShellComicPlaygroundIndexRoute
  '/member-list': typeof AuthenticatedShellMemberListIndexRoute
  '/settings': typeof AuthenticatedShellSettingsIndexRoute
  '/system-mail': typeof AuthenticatedShellSystemMailIndexRoute
  '/utilities': typeof AuthenticatedShellUtilitiesIndexRoute
  '/workspace': typeof AuthenticatedShellWorkspaceIndexRoute
  '/translator/$chapterId/$pageId': typeof AuthenticatedTranslatorChapterIdPageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_shell': typeof AuthenticatedShellRouteRouteWithChildren
  '/_authenticated/translator': typeof AuthenticatedTranslatorRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/_shell/': typeof AuthenticatedShellIndexRoute
  '/_authenticated/_shell/comic-playground/': typeof AuthenticatedShellComicPlaygroundIndexRoute
  '/_authenticated/_shell/member-list/': typeof AuthenticatedShellMemberListIndexRoute
  '/_authenticated/_shell/settings/': typeof AuthenticatedShellSettingsIndexRoute
  '/_authenticated/_shell/system-mail/': typeof AuthenticatedShellSystemMailIndexRoute
  '/_authenticated/_shell/utilities/': typeof AuthenticatedShellUtilitiesIndexRoute
  '/_authenticated/_shell/workspace/': typeof AuthenticatedShellWorkspaceIndexRoute
  '/_authenticated/translator/$chapterId/$pageId/': typeof AuthenticatedTranslatorChapterIdPageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/translator'
    | '/login/'
    | '/comic-playground/'
    | '/member-list/'
    | '/settings/'
    | '/system-mail/'
    | '/utilities/'
    | '/workspace/'
    | '/translator/$chapterId/$pageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/translator'
    | '/login'
    | '/comic-playground'
    | '/member-list'
    | '/settings'
    | '/system-mail'
    | '/utilities'
    | '/workspace'
    | '/translator/$chapterId/$pageId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_shell'
    | '/_authenticated/translator'
    | '/login/'
    | '/_authenticated/_shell/'
    | '/_authenticated/_shell/comic-playground/'
    | '/_authenticated/_shell/member-list/'
    | '/_authenticated/_shell/settings/'
    | '/_authenticated/_shell/system-mail/'
    | '/_authenticated/_shell/utilities/'
    | '/_authenticated/_shell/workspace/'
    | '/_authenticated/translator/$chapterId/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/translator': {
      id: '/_authenticated/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof AuthenticatedTranslatorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell/': {
      id: '/_authenticated/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/comic-playground/': {
      id: '/_authenticated/_shell/comic-playground/'
      path: '/comic-playground'
      fullPath: '/comic-playground/'
      preLoaderRoute: typeof AuthenticatedShellComicPlaygroundIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/member-list/': {
      id: '/_authenticated/_shell/member-list/'
      path: '/member-list'
      fullPath: '/member-list/'
      preLoaderRoute: typeof AuthenticatedShellMemberListIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/settings/': {
      id: '/_authenticated/_shell/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedShellSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/system-mail/': {
      id: '/_authenticated/_shell/system-mail/'
      path: '/system-mail'
      fullPath: '/system-mail/'
      preLoaderRoute: typeof AuthenticatedShellSystemMailIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/utilities/': {
      id: '/_authenticated/_shell/utilities/'
      path: '/utilities'
      fullPath: '/utilities/'
      preLoaderRoute: typeof AuthenticatedShellUtilitiesIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/workspace/': {
      id: '/_authenticated/_shell/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedShellWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/translator/$chapterId/$pageId/': {
      id: '/_authenticated/translator/$chapterId/$pageId/'
      path: '/$chapterId/$pageId'
      fullPath: '/translator/$chapterId/$pageId/'
      preLoaderRoute: typeof AuthenticatedTranslatorChapterIdPageIdIndexRouteImport
      parentRoute: typeof AuthenticatedTranslatorRouteRoute
    }
  }
}

interface AuthenticatedShellRouteRouteChildren {
  AuthenticatedShellIndexRoute: typeof AuthenticatedShellIndexRoute
  AuthenticatedShellComicPlaygroundIndexRoute: typeof AuthenticatedShellComicPlaygroundIndexRoute
  AuthenticatedShellMemberListIndexRoute: typeof AuthenticatedShellMemberListIndexRoute
  AuthenticatedShellSettingsIndexRoute: typeof AuthenticatedShellSettingsIndexRoute
  AuthenticatedShellSystemMailIndexRoute: typeof AuthenticatedShellSystemMailIndexRoute
  AuthenticatedShellUtilitiesIndexRoute: typeof AuthenticatedShellUtilitiesIndexRoute
  AuthenticatedShellWorkspaceIndexRoute: typeof AuthenticatedShellWorkspaceIndexRoute
}

const AuthenticatedShellRouteRouteChildren: AuthenticatedShellRouteRouteChildren =
  {
    AuthenticatedShellIndexRoute: AuthenticatedShellIndexRoute,
    AuthenticatedShellComicPlaygroundIndexRoute:
      AuthenticatedShellComicPlaygroundIndexRoute,
    AuthenticatedShellMemberListIndexRoute:
      AuthenticatedShellMemberListIndexRoute,
    AuthenticatedShellSettingsIndexRoute: AuthenticatedShellSettingsIndexRoute,
    AuthenticatedShellSystemMailIndexRoute:
      AuthenticatedShellSystemMailIndexRoute,
    AuthenticatedShellUtilitiesIndexRoute:
      AuthenticatedShellUtilitiesIndexRoute,
    AuthenticatedShellWorkspaceIndexRoute:
      AuthenticatedShellWorkspaceIndexRoute,
  }

const AuthenticatedShellRouteRouteWithChildren =
  AuthenticatedShellRouteRoute._addFileChildren(
    AuthenticatedShellRouteRouteChildren,
  )

interface AuthenticatedTranslatorRouteRouteChildren {
  AuthenticatedTranslatorChapterIdPageIdIndexRoute: typeof AuthenticatedTranslatorChapterIdPageIdIndexRoute
}

const AuthenticatedTranslatorRouteRouteChildren: AuthenticatedTranslatorRouteRouteChildren =
  {
    AuthenticatedTranslatorChapterIdPageIdIndexRoute:
      AuthenticatedTranslatorChapterIdPageIdIndexRoute,
  }

const AuthenticatedTranslatorRouteRouteWithChildren =
  AuthenticatedTranslatorRouteRoute._addFileChildren(
    AuthenticatedTranslatorRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedShellRouteRoute: typeof AuthenticatedShellRouteRouteWithChildren
  AuthenticatedTranslatorRouteRoute: typeof AuthenticatedTranslatorRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedShellRouteRoute: AuthenticatedShellRouteRouteWithChildren,
  AuthenticatedTranslatorRouteRoute:
    AuthenticatedTranslatorRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
