import {
  type UnitInfo,
  unitProofreadText,
  unitTranslatedText,
} from "@/routes/_authenticated/translator/business/unit/unit";
import type { Project } from "@/routes/_authenticated/translator/business/unit/project";
import type { UserInfo } from "@/routes/business/identity/user";

export const DEMO_IMAGE =
  "data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%27600%27 height=%27800%27 viewBox=%270 0 600 800%27%3E%3Crect width=%27600%27 height=%27800%27 fill=%27%23e8e6dc%27/%3E%3Cpath d=%27M0 600L180 330l110 170 90-110 220 210v200H0z%27 fill=%27%2398aa91%27/%3E%3C/svg%3E";

export const TRANSLATOR_ID = "mock-translator";
export const PROOFREADER_ID = "mock-proofreader";

export const mockUnits = (
  [
    {
      id: "1",
      index: 0,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.22,
      yCoord: 0.18,
      isProofread: false,
      translatedText: "——你在这里啊，终于找到你了。",
    },
    {
      id: "2",
      index: 1,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.65,
      yCoord: 0.28,
      isProofread: false,
    },
    {
      id: "3",
      index: 2,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.38,
      yCoord: 0.52,
      isProofread: true,
      translatedText: "不……这不可能。",
      proofreadText: "不……这怎么可能。",
    },
    {
      id: "4",
      index: 3,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.72,
      yCoord: 0.62,
      isProofread: false,
      translatedText: "冷静下来，听我说。",
    },
    {
      id: "5",
      index: 4,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.48,
      yCoord: 0.8,
      isProofread: false,
    },
    {
      id: "6",
      index: 5,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.12,
      yCoord: 0.12,
      isProofread: false,
      translatedText: "这里发生了什么？",
    },
    {
      id: "7",
      index: 6,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.28,
      yCoord: 0.2,
      isProofread: false,
    },
    {
      id: "8",
      index: 7,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.54,
      yCoord: 0.33,
      isProofread: false,
      translatedText: "快点！",
    },
    {
      id: "9",
      index: 8,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.41,
      yCoord: 0.45,
      isProofread: true,
      translatedText: "别乱动。",
      proofreadText: "别动！",
    },
    {
      id: "10",
      index: 9,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.62,
      yCoord: 0.5,
      isProofread: false,
    },
    {
      id: "11",
      index: 10,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.33,
      yCoord: 0.6,
      isProofread: false,
      translatedText: "你还好吗？",
    },
    {
      id: "12",
      index: 11,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.7,
      yCoord: 0.22,
      isProofread: false,
    },
    {
      id: "13",
      index: 12,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.18,
      yCoord: 0.7,
      isProofread: true,
      translatedText: "我没事。",
      proofreadText: "我没事，谢谢。",
    },
    {
      id: "14",
      index: 13,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.9,
      yCoord: 0.4,
      isProofread: false,
      translatedText: "我们得走了。",
    },
    {
      id: "15",
      index: 14,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.44,
      yCoord: 0.88,
      isProofread: false,
    },
    {
      id: "16",
      index: 15,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.2,
      yCoord: 0.3,
      isProofread: false,
    },
    {
      id: "17",
      index: 16,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.6,
      yCoord: 0.12,
      isProofread: false,
      translatedText: "看那边！",
    },
    {
      id: "18",
      index: 17,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.27,
      yCoord: 0.44,
      isProofread: false,
    },
    {
      id: "19",
      index: 18,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.5,
      yCoord: 0.5,
      isProofread: true,
      translatedText: "别信他。",
      proofreadText: "别听他的话。",
    },
    {
      id: "20",
      index: 19,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.66,
      yCoord: 0.66,
      isProofread: false,
    },
    {
      id: "21",
      index: 20,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.11,
      yCoord: 0.2,
      isProofread: false,
      translatedText: "怎么可能？",
    },
    {
      id: "22",
      index: 21,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.35,
      yCoord: 0.27,
      isProofread: false,
    },
    {
      id: "23",
      index: 22,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.46,
      yCoord: 0.32,
      isProofread: false,
      translatedText: "小心！",
    },
    {
      id: "24",
      index: 23,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.58,
      yCoord: 0.42,
      isProofread: true,
      translatedText: "我来帮你。",
      proofreadText: "我会帮你。",
    },
    {
      id: "25",
      index: 24,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.78,
      yCoord: 0.55,
      isProofread: false,
    },
    {
      id: "26",
      index: 25,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.49,
      yCoord: 0.74,
      isProofread: false,
    },
    {
      id: "27",
      index: 26,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.36,
      yCoord: 0.82,
      isProofread: false,
      translatedText: "别放弃。",
    },
    {
      id: "28",
      index: 27,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.82,
      yCoord: 0.2,
      isProofread: false,
    },
    {
      id: "29",
      index: 28,
      isBubble: true,
      isFlagged: false,
      xCoord: 0.14,
      yCoord: 0.58,
      isProofread: false,
    },
    {
      id: "30",
      index: 29,
      isBubble: false,
      isFlagged: false,
      xCoord: 0.95,
      yCoord: 0.92,
      isProofread: true,
      translatedText: "结束了。",
      proofreadText: "终于结束了。",
    },
  ] satisfies UnitInfo[]
).map(
  (unit): UnitInfo => ({
    ...unit,
    ...(unitTranslatedText(unit) && { translatorId: TRANSLATOR_ID }),
    ...(unitProofreadText(unit) && { proofreaderId: PROOFREADER_ID }),
  }),
);

export const mockUsers = new Map<string, UserInfo>([
  [
    TRANSLATOR_ID,
    {
      id: TRANSLATOR_ID,
      qq: "10001",
      name: "森川秋",
      avatarUrl: "",
      isSuperAdmin: false,
      lastActiveAt: Date.now(),
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  ],
  [
    PROOFREADER_ID,
    {
      id: PROOFREADER_ID,
      qq: "10002",
      name: "林澄",
      avatarUrl: "",
      isSuperAdmin: false,
      lastActiveAt: Date.now(),
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  ],
]);

export const mockProject: Project = {
  id: "project-1",
  title: "测试漫画",
  author: "Demo",
  pageCount: 3,
  totalUnitCount: 15,
  translatedUnitCount: 8,
  proofreadUnitCount: 3,
  pages: [
    {
      id: "page-1",
      chapterId: "chapter-1",
      index: 0,
      imageUrl: DEMO_IMAGE,
      imageOptimizedUrl: DEMO_IMAGE,
      isUploaded: true,
      creatorId: "mock-user",
      totalUnitCount: 5,
      translatedUnitCount: 3,
      proofreadUnitCount: 1,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: "page-2",
      chapterId: "chapter-1",
      index: 1,
      imageUrl: DEMO_IMAGE,
      imageOptimizedUrl: DEMO_IMAGE,
      isUploaded: true,
      creatorId: "mock-user",
      totalUnitCount: 5,
      translatedUnitCount: 3,
      proofreadUnitCount: 1,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: "page-3",
      chapterId: "chapter-1",
      index: 2,
      imageUrl: DEMO_IMAGE,
      imageOptimizedUrl: DEMO_IMAGE,
      isUploaded: true,
      creatorId: "mock-user",
      totalUnitCount: 5,
      translatedUnitCount: 2,
      proofreadUnitCount: 1,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  ],
};
